# Generated by Django 3.1.1 on 2020-11-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200912_2205'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NflTeamRegularSeasonRecords',
            new_name='NflTeamRegularSeasonRecord',
        ),
    ]
