# Generated by Django 3.1.1 on 2020-12-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0007_nflstanding_team_id'),
        ('stats', '0002_auto_20201128_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflteamregularseasonrecord',
            name='loss_count',
        ),
        migrations.RemoveField(
            model_name='nflteamregularseasonrecord',
            name='season_type',
        ),
        migrations.RemoveField(
            model_name='nflteamregularseasonrecord',
            name='season_year',
        ),
        migrations.RemoveField(
            model_name='nflteamregularseasonrecord',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='nflteamregularseasonrecord',
            name='tie_count',
        ),
        migrations.RemoveField(
            model_name='nflteamregularseasonrecord',
            name='win_count',
        ),
        migrations.AddField(
            model_name='nflteamregularseasonrecord',
            name='standing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standing_id', to='standings.nflstanding'),
        ),
    ]
