# Generated by Django 3.1.1 on 2020-12-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20201202_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteamregularseasonrecord',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nflteamregularseasonrecord',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nflteamregularseasonrecord',
            name='season_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
