# Generated by Django 3.1.1 on 2020-12-03 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0007_nflstanding_team_id'),
        ('stats', '0004_auto_20201202_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflteamregularseasonrecord',
            name='standing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standing', to='standings.nflstanding'),
        ),
    ]
