# Generated by Django 3.1.1 on 2020-12-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20201130_1336'),
        ('schedule', '0023_auto_20201130_1642'),
        ('standings', '0007_nflstanding_team_id'),
        ('stats', '0006_auto_20201204_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='NflGameStatsFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField(blank=True, null=True)),
                ('season_type', models.CharField(default='', max_length=50)),
                ('home_team_rushing_attempts_count', models.PositiveIntegerField(default=0)),
                ('home_team_total_rushing_yards', models.PositiveIntegerField(default=0)),
                ('home_team_avg_yards_per_rush', models.FloatField(default=0.0)),
                ('away_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_id', to='teams.nflteam')),
                ('game_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='schedule.nflgame')),
                ('home_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_id', to='teams.nflteam')),
            ],
        ),
        migrations.RenameField(
            model_name='nflteamregularseasonstats',
            old_name='rushing_avg_yards',
            new_name='rushing_avg_yards_per_rush',
        ),
        migrations.AddField(
            model_name='nflteamregularseasonrecord',
            name='season_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nflteamregularseasonrecord',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_team', to='teams.nflteam'),
        ),
        migrations.AddField(
            model_name='nflteamregularseasonstats',
            name='standing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standing', to='standings.nflstanding'),
        ),
        migrations.DeleteModel(
            name='NflGameStats',
        ),
    ]
