# Generated by Django 3.1.1 on 2020-09-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='team',
        ),
    ]
