# Generated by Django 3.1.1 on 2020-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0003_auto_20200915_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='standing',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
