# Generated by Django 3.1.1 on 2020-11-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0004_auto_20200915_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='season_year',
            field=models.PositiveIntegerField(),
        ),
    ]
