# Generated by Django 3.1.1 on 2020-12-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20201130_1336'),
        ('standings', '0006_auto_20201201_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflstanding',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.nflteam'),
        ),
    ]
