# Generated by Django 3.1.1 on 2020-09-13 01:15

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('abr', models.CharField(max_length=10)),
                ('conference', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('league', models.CharField(max_length=50)),
                ('primary_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('secondary_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('logo', models.ImageField(upload_to='nfl/logos')),
            ],
        ),
    ]
