# Generated by Django 3.1.1 on 2020-09-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='secondary_color',
        ),
    ]
