# Generated by Django 3.1.1 on 2020-09-13 02:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
