# Generated by Django 3.1.1 on 2020-09-13 02:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200912_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='team',
            name='tertiary_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
