# Generated by Django 3.1.1 on 2020-11-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20201130_1316'),
        ('stats', '0002_auto_20201128_1847'),
        ('teams', '0004_auto_20200912_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='NflTeam',
        ),
    ]
