# Generated by Django 3.1.4 on 2020-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NbaDfsPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('fantasy_points_per_game', models.FloatField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('team_alias', models.CharField(max_length=10)),
                ('opponent_team_alias', models.CharField(max_length=10)),
                ('injury_indicator', models.CharField(max_length=50)),
                ('injury_details', models.CharField(max_length=50)),
                ('tier', models.CharField(max_length=50)),
            ],
        ),
    ]
