# Generated by Django 3.1.4 on 2020-12-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfsPlayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbadfsplayer',
            name='injury_details',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nbadfsplayer',
            name='injury_indicator',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nbadfsplayer',
            name='nickname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nbadfsplayer',
            name='tier',
            field=models.CharField(default='', max_length=50),
        ),
    ]
