# Generated by Django 3.1.4 on 2020-12-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfsPlayers', '0002_auto_20201224_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbadfsplayer',
            name='dfs_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
