# Generated by Django 3.1.1 on 2020-11-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField()),
                ('season_type', models.CharField(max_length=50)),
                ('game_id', models.CharField(max_length=50)),
                ('league', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('game_datetime', models.DateTimeField(blank=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('stadium_name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('surface', models.CharField(max_length=50)),
                ('roof_type', models.CharField(max_length=50)),
                ('home_team_name', models.CharField(max_length=100)),
                ('away_team_name', models.CharField(max_length=100)),
                ('home_team_alias', models.CharField(max_length=10)),
                ('broadcast_network', models.CharField(max_length=50)),
                ('home_team_points', models.PositiveSmallIntegerField(default=0)),
                ('away_team_points', models.PositiveSmallIntegerField(default=0)),
                ('home_team_quarter_1_points', models.PositiveSmallIntegerField(default=0)),
                ('away_team_quarter_1_points', models.PositiveSmallIntegerField(default=0)),
                ('home_team_quarter_2_points', models.PositiveSmallIntegerField(default=0)),
                ('away_team_quarter_2_points', models.PositiveSmallIntegerField(default=0)),
                ('home_team_quarter_3_points', models.PositiveSmallIntegerField(default=0)),
                ('away_team_quarter_3_points', models.PositiveSmallIntegerField(default=0)),
                ('home_team_quarter_4_points', models.PositiveSmallIntegerField(default=0)),
                ('away_team_quarter_4_points', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
