# Generated by Django 3.1.1 on 2020-11-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='attendance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='weather',
            field=models.CharField(default='', max_length=100),
        ),
    ]
