# Generated by Django 3.1.1 on 2020-11-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20201101_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='away_team_alias',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='away_team_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home_team_alias',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home_team_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
