# Generated by Django 3.1.1 on 2020-11-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_week_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='game_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
