# Generated by Django 3.1.1 on 2020-11-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20201106_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='weather_conditions',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='weather_temp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='weather_wind',
            field=models.CharField(default='', max_length=100),
        ),
    ]
