# Generated by Django 3.1.1 on 2020-11-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20201124_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='home_team',
        ),
    ]
