# Generated by Django 3.1.1 on 2020-11-28 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200912_2205'),
        ('schedule', '0020_auto_20201127_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='away_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_id', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_id', to='teams.team'),
        ),
    ]
