# Generated by Django 3.1.1 on 2020-11-30 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20201130_1336'),
        ('schedule', '0022_auto_20201130_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflgame',
            name='away_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='teams.nflteam'),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='home_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.nflteam'),
        ),
    ]
