# Generated by Django 3.1.1 on 2020-12-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NflPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_player_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('abbreviated_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('position', models.CharField(default='', max_length=25)),
                ('high_school', models.CharField(default='', max_length=50)),
                ('college', models.CharField(default='', max_length=50)),
                ('college_conference', models.CharField(default='', max_length=50)),
                ('rookie_year', models.PositiveIntegerField(blank=True, null=True)),
                ('jersey_number', models.PositiveSmallIntegerField()),
                ('year_drafted', models.PositiveIntegerField()),
                ('draft_round', models.PositiveSmallIntegerField()),
                ('number_drafted', models.PositiveIntegerField()),
                ('team_drafted_name', models.CharField(default='', max_length=50)),
                ('team_drafted_city', models.CharField(default='', max_length=50)),
                ('team_drafted_alias', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
