# Generated by Django 3.1.1 on 2020-12-08 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20201130_1336'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflplayer',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_team', to='teams.nflteam'),
        ),
    ]
