# Generated by Django 3.1.1 on 2020-12-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20201210_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflplayer',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
